Add method to get flyover redeem script from the powpeg redeem script
rsksmart/powpeg-redeemscript-parser pull request #7
Opened 2022-06-17 20:02 UTC by marcos-iov

2022-06-20 15:03 UTC, nathanieliov requested changes

2022-06-20 15:03 UTC, nathanieliov commented on test/redeem-script-parser-test.js
> +        )).to.throw('erpBtcPublicKeys should be an array');
```suggestion
        )).to.throw('erpBtcPublicKeys should be an array');
        
        // fail because there is no csvValue
        expect(() => redeemScriptParser.getFlyoverErpRedeemScript(
          publicKeys,
          erpPublicKeys,
          null,
          dHash
        )).to.throw('csvValue is required');
```

2022-06-20 17:30 UTC, nathanieliov commented on index.js
>      getAddressFromRedeemSript,
Let's create a new method to get an address directly given a `reedemScript`, `dHash`, and a `network`. Why? I just realized that in the alphanet tests, I mostly need the address, not the formatted `redeemScript`, which I only use to call the `getAddressFromRedeemSript` after.

Let me know if you think can be useful to add this method.

![image](https://user-images.githubusercontent.com/94651730/174652383-83e07c36-d452-4ae1-8413-29e41fde2a07.png)

2022-06-20 20:28 UTC, marcos-iov commented on test/redeem-script-parser-test.js
> +        expect(() => redeemScriptParser.getFlyoverRedeemScriptFromPublicKeys(publicKeys, '')).to.throw('derivationArgsHash must be hash represented as a 64 characters string');
Makes sense. Thanks for the idea!

2022-06-20 20:30 UTC, marcos-iov commented on test/redeem-script-parser-test.js
> +        )).to.throw('erpBtcPublicKeys should be an array');
Good catch. Thanks!

2022-06-28 22:50 UTC, nathanieliov commented on index.js
>      getAddressFromRedeemSript,
We decided to leave it as it is because my proposal is actually a bit redundant.

2022-06-28 23:23 UTC, nathanieliov approved these changes

2022-06-28 23:23 UTC, merged